import { Router } from 'express';
import { accountStatus, login, logout, me, register } from '../controllers/authController.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
router.get('/account-status', accountStatus);
router.post('/register', register);
router.post('/login', login);
router.post('/logout', logout);
router.get('/me', requireAuth, me);
export default router;
